name: Hive
main: net.novauniverse.games.hive.NovaHive
description: Novauniverse Hive
version: 1.0
depend: [NovaCore, NovaCoreGameEngine, HolographicDisplays]
softdepend: [NovaGamesTarget]
api-version: 1.16